version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  reviewers:
  - alexanderbez
  - fedekunze
  labels:
  - automerge
  - dependencies
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/docs"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  reviewers:
  - fadeev
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
