FROM bufbuild/buf:latest as builder

FROM golang:1.18-alpine

RUN apk add --no-cache git build-base bash ca-certificates

ENV GOBIN=/usr/local/bin
ENV PATH=$GOBIN:$PATH

ENV GOLANG_PROTOBUF_VERSION=1.3.5 \
    GOGO_PROTOBUF_VERSION=1.3.2 \
    GRPC_GATEWAY_VERSION=1.14.7 \
    PROTOC_GEN_DOC_VERSION=1.5.1

RUN go install github.com/golang/protobuf/protoc-gen-go@v${GOLANG_PROTOBUF_VERSION}
RUN go install github.com/gogo/protobuf/protoc-gen-gogo@v${GOGO_PROTOBUF_VERSION}
RUN go install github.com/gogo/protobuf/protoc-gen-gogofast@v${GOGO_PROTOBUF_VERSION}
RUN go install github.com/gogo/protobuf/protoc-gen-gogofaster@v${GOGO_PROTOBUF_VERSION}
RUN go install github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway@v${GRPC_GATEWAY_VERSION}
RUN go install github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger@v${GRPC_GATEWAY_VERSION}
# RUN go install github.com/cosmos/gogoproto/protoc-gen-gocosmos@latest

RUN go install github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc@v${PROTOC_GEN_DOC_VERSION}

RUN apk add --no-cache nodejs npm
RUN npm install -g swagger-combine

COPY --from=builder /usr/local/bin /usr/local/bin

WORKDIR /workspace
